cmake_minimum_required(VERSION 3.25)

foreach(GARGANTUAN_REQUIRED_VARIABLE
	GARGANTUAN_PACKAGER
	GARGANTUAN_SERVER_RUNTIME_DISTRIBUTION
	GARGANTUAN_PROJECT_ROOT
	GARGANTUAN_PACKAGE_TEST_ROOT
)
	if(NOT DEFINED ${GARGANTUAN_REQUIRED_VARIABLE} OR "${${GARGANTUAN_REQUIRED_VARIABLE}}" STREQUAL "")
		message(FATAL_ERROR "Missing ${GARGANTUAN_REQUIRED_VARIABLE}")
	endif()
endforeach()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef GARGANTUAN_PACKAGE_SUFFIX)
if(DEFINED ENV{TEMP} AND NOT "$ENV{TEMP}" STREQUAL "")
	file(TO_CMAKE_PATH "$ENV{TEMP}" GARGANTUAN_PACKAGE_TEST_BASE)
elseif(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
	file(TO_CMAKE_PATH "$ENV{TMPDIR}" GARGANTUAN_PACKAGE_TEST_BASE)
else()
	set(GARGANTUAN_PACKAGE_TEST_BASE "${GARGANTUAN_PACKAGE_TEST_ROOT}")
endif()
set(GARGANTUAN_WORKSPACE
	"${GARGANTUAN_PACKAGE_TEST_BASE}/gss-${GARGANTUAN_PACKAGE_SUFFIX}")
set(GARGANTUAN_PACKAGE "${GARGANTUAN_WORKSPACE}/FirstCompleteGameServer")
file(MAKE_DIRECTORY "${GARGANTUAN_WORKSPACE}")

function(GargantuanServerPackageFailure MessageText)
	file(REMOVE_RECURSE "${GARGANTUAN_WORKSPACE}")
	string(CONCAT FailureText ${ARGV})
	message(FATAL_ERROR "${FailureText}")
endfunction()

execute_process(
	COMMAND "${GARGANTUAN_PACKAGER}" build
		--project "${GARGANTUAN_PROJECT_ROOT}"
		--output "${GARGANTUAN_PACKAGE}"
		--runtime "${GARGANTUAN_SERVER_RUNTIME_DISTRIBUTION}"
		--configuration Release
	WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
	RESULT_VARIABLE GARGANTUAN_BUILD_RESULT
	OUTPUT_VARIABLE GARGANTUAN_BUILD_OUTPUT
	ERROR_VARIABLE GARGANTUAN_BUILD_ERROR
	TIMEOUT 60
)
if(NOT GARGANTUAN_BUILD_RESULT EQUAL 0)
	GargantuanServerPackageFailure(
		"Dedicated Server package build failed: ${GARGANTUAN_BUILD_OUTPUT}${GARGANTUAN_BUILD_ERROR}"
	)
endif()

if(WIN32)
	set(GARGANTUAN_SERVER "${GARGANTUAN_PACKAGE}/GargantuanServer.exe")
else()
	set(GARGANTUAN_SERVER "${GARGANTUAN_PACKAGE}/GargantuanServer")
endif()
if(NOT EXISTS "${GARGANTUAN_SERVER}")
	GargantuanServerPackageFailure("Dedicated Server executable was not staged")
endif()

execute_process(
	COMMAND "${CMAKE_COMMAND}" -E env
		"SDL_VIDEODRIVER=foundation1-invalid"
		"SDL_AUDIODRIVER=foundation1-invalid"
		"${GARGANTUAN_SERVER}" --startup-smoke --max-ticks 12
	WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
	RESULT_VARIABLE GARGANTUAN_SERVER_RESULT
	OUTPUT_VARIABLE GARGANTUAN_SERVER_OUTPUT
	ERROR_VARIABLE GARGANTUAN_SERVER_ERROR
	TIMEOUT 60
)
if(NOT GARGANTUAN_SERVER_RESULT EQUAL 0)
	GargantuanServerPackageFailure(
		"Dedicated Server package smoke failed (${GARGANTUAN_SERVER_RESULT}): "
		"${GARGANTUAN_SERVER_OUTPUT}${GARGANTUAN_SERVER_ERROR}"
	)
endif()

# This error occurs after Engine construction, not in the CLI/config parser.
# Exception cleanup must retain the renderer until Engine::Destroy completes.
execute_process(
	COMMAND "${GARGANTUAN_SERVER}" --startup-smoke --max-ticks 12
		--content-residency on-demand --content-lifecycle-smoke workspace/nonexistent-unwind-regression
	WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
	RESULT_VARIABLE GARGANTUAN_UNWIND_RESULT
	OUTPUT_VARIABLE GARGANTUAN_UNWIND_OUTPUT ERROR_VARIABLE GARGANTUAN_UNWIND_ERROR
	TIMEOUT 60)
if(NOT GARGANTUAN_UNWIND_RESULT EQUAL 7 OR
	NOT "${GARGANTUAN_UNWIND_OUTPUT}${GARGANTUAN_UNWIND_ERROR}" MATCHES "trusted content smoke key is absent")
	GargantuanServerPackageFailure(
		"Dedicated Server exception cleanup failed (${GARGANTUAN_UNWIND_RESULT}): "
		"${GARGANTUAN_UNWIND_OUTPUT}${GARGANTUAN_UNWIND_ERROR}")
endif()

file(REMOVE_RECURSE "${GARGANTUAN_WORKSPACE}")
message(STATUS "Dedicated Server package/headless startup smoke passed")
