cmake_minimum_required(VERSION 3.25)

foreach(GARGANTUAN_REQUIRED_VARIABLE
	GARGANTUAN_PACKAGER
	GARGANTUAN_PROJECT_ROOT
	GARGANTUAN_PACKAGE_TEST_ROOT
)
	if(NOT DEFINED ${GARGANTUAN_REQUIRED_VARIABLE} OR "${${GARGANTUAN_REQUIRED_VARIABLE}}" STREQUAL "")
		message(FATAL_ERROR "Missing ${GARGANTUAN_REQUIRED_VARIABLE}")
	endif()
endforeach()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef GARGANTUAN_PACKAGE_SUFFIX)
if(DEFINED ENV{TEMP} AND NOT "$ENV{TEMP}" STREQUAL "")
	file(TO_CMAKE_PATH "$ENV{TEMP}" GARGANTUAN_PACKAGE_TEST_BASE)
elseif(DEFINED ENV{TMPDIR} AND NOT "$ENV{TMPDIR}" STREQUAL "")
	file(TO_CMAKE_PATH "$ENV{TMPDIR}" GARGANTUAN_PACKAGE_TEST_BASE)
else()
	set(GARGANTUAN_PACKAGE_TEST_BASE "${GARGANTUAN_PACKAGE_TEST_ROOT}")
endif()
set(GARGANTUAN_WORKSPACE "${GARGANTUAN_PACKAGE_TEST_BASE}/gargantuan-package-smoke-${GARGANTUAN_PACKAGE_SUFFIX}")
set(GARGANTUAN_PACKAGE "${GARGANTUAN_WORKSPACE}/FirstCompleteGame")
set(GARGANTUAN_RELOCATED "${GARGANTUAN_WORKSPACE}/RelocatedGame")
file(MAKE_DIRECTORY "${GARGANTUAN_WORKSPACE}")

function(GargantuanPackageFailure MessageText)
	file(REMOVE_RECURSE "${GARGANTUAN_WORKSPACE}")
	message(FATAL_ERROR "${MessageText}")
endfunction()

execute_process(
	COMMAND "${GARGANTUAN_PACKAGER}" build
		--project "${GARGANTUAN_PROJECT_ROOT}"
		--output "${GARGANTUAN_PACKAGE}"
		--configuration Release
	WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
	RESULT_VARIABLE GARGANTUAN_BUILD_RESULT
	OUTPUT_VARIABLE GARGANTUAN_BUILD_OUTPUT
	ERROR_VARIABLE GARGANTUAN_BUILD_ERROR
	TIMEOUT 60
)
if(NOT GARGANTUAN_BUILD_RESULT EQUAL 0)
	GargantuanPackageFailure("FirstCompleteGame package build failed: ${GARGANTUAN_BUILD_OUTPUT}${GARGANTUAN_BUILD_ERROR}")
endif()

execute_process(
	COMMAND "${GARGANTUAN_PACKAGER}" validate "${GARGANTUAN_PACKAGE}"
	RESULT_VARIABLE GARGANTUAN_VALIDATE_RESULT
	OUTPUT_VARIABLE GARGANTUAN_VALIDATE_OUTPUT
	ERROR_VARIABLE GARGANTUAN_VALIDATE_ERROR
	TIMEOUT 30
)
if(NOT GARGANTUAN_VALIDATE_RESULT EQUAL 0)
	GargantuanPackageFailure("FirstCompleteGame package validation failed: ${GARGANTUAN_VALIDATE_OUTPUT}${GARGANTUAN_VALIDATE_ERROR}")
endif()

execute_process(
	COMMAND "${GARGANTUAN_PACKAGER}" inspect "${GARGANTUAN_PACKAGE}"
	RESULT_VARIABLE GARGANTUAN_INSPECT_RESULT
	OUTPUT_VARIABLE GARGANTUAN_INSPECT_OUTPUT
	ERROR_VARIABLE GARGANTUAN_INSPECT_ERROR
	TIMEOUT 30
)
if(NOT GARGANTUAN_INSPECT_RESULT EQUAL 0 OR
	NOT GARGANTUAN_INSPECT_OUTPUT MATCHES "\"ProjectId\":\"4f9ec7db36ca4d21a1b04134dd68dfd2\"")
	GargantuanPackageFailure("FirstCompleteGame package inspection failed: ${GARGANTUAN_INSPECT_OUTPUT}${GARGANTUAN_INSPECT_ERROR}")
endif()

file(COPY "${GARGANTUAN_PACKAGE}/" DESTINATION "${GARGANTUAN_RELOCATED}")
if(WIN32)
	set(GARGANTUAN_PLAYER "${GARGANTUAN_RELOCATED}/GargantuanPlayer.exe")
else()
	set(GARGANTUAN_PLAYER "${GARGANTUAN_RELOCATED}/GargantuanPlayer")
endif()
execute_process(
	COMMAND "${GARGANTUAN_PLAYER}" --headless --startup-smoke
	WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
	RESULT_VARIABLE GARGANTUAN_HEADLESS_RESULT
	OUTPUT_VARIABLE GARGANTUAN_HEADLESS_OUTPUT
	ERROR_VARIABLE GARGANTUAN_HEADLESS_ERROR
	TIMEOUT 60
)
if(NOT GARGANTUAN_HEADLESS_RESULT EQUAL 0)
	GargantuanPackageFailure("Relocated headless player smoke failed: ${GARGANTUAN_HEADLESS_OUTPUT}${GARGANTUAN_HEADLESS_ERROR}")
endif()

if(WIN32)
	set(GARGANTUAN_ORIGINAL_PATH "$ENV{PATH}")
	set(ENV{PATH} "$ENV{SystemRoot}/System32;$ENV{SystemRoot}")
	execute_process(
		COMMAND "${GARGANTUAN_PLAYER}" --headless --startup-smoke
		WORKING_DIRECTORY "${GARGANTUAN_PACKAGE_TEST_BASE}"
		RESULT_VARIABLE GARGANTUAN_CLEAN_PATH_RESULT
		OUTPUT_VARIABLE GARGANTUAN_CLEAN_PATH_OUTPUT
		ERROR_VARIABLE GARGANTUAN_CLEAN_PATH_ERROR
		TIMEOUT 60
	)
	set(ENV{PATH} "${GARGANTUAN_ORIGINAL_PATH}")
	if(NOT GARGANTUAN_CLEAN_PATH_RESULT EQUAL 0)
		GargantuanPackageFailure("Minimal-PATH native runtime closure failed: ${GARGANTUAN_CLEAN_PATH_OUTPUT}${GARGANTUAN_CLEAN_PATH_ERROR}")
	endif()
endif()

if(WIN32 AND GARGANTUAN_RUN_GRAPHICAL_SMOKE)
	execute_process(
		COMMAND "${GARGANTUAN_PLAYER}" --startup-smoke --max-frames 4
		WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
		RESULT_VARIABLE GARGANTUAN_GRAPHICAL_RESULT
		OUTPUT_VARIABLE GARGANTUAN_GRAPHICAL_OUTPUT
		ERROR_VARIABLE GARGANTUAN_GRAPHICAL_ERROR
		TIMEOUT 60
	)
	if(NOT GARGANTUAN_GRAPHICAL_RESULT EQUAL 0)
		GargantuanPackageFailure("Windows graphical player smoke failed: ${GARGANTUAN_GRAPHICAL_OUTPUT}${GARGANTUAN_GRAPHICAL_ERROR}")
	endif()
endif()

function(GargantuanExpectRejectedPackage PackageRoot FailureName)
	if(WIN32)
		set(GARGANTUAN_REJECTED_PLAYER "${PackageRoot}/GargantuanPlayer.exe")
	else()
		set(GARGANTUAN_REJECTED_PLAYER "${PackageRoot}/GargantuanPlayer")
	endif()
	execute_process(
		COMMAND "${GARGANTUAN_REJECTED_PLAYER}" --headless --startup-smoke
		WORKING_DIRECTORY "${GARGANTUAN_WORKSPACE}"
		RESULT_VARIABLE GARGANTUAN_REJECTED_RESULT
		OUTPUT_QUIET
		ERROR_QUIET
		TIMEOUT 30
	)
	if(GARGANTUAN_REJECTED_RESULT EQUAL 0)
		GargantuanPackageFailure("Packaged player accepted ${FailureName}")
	endif()
endfunction()

set(GARGANTUAN_INCOMPATIBLE "${GARGANTUAN_WORKSPACE}/IncompatibleGame")
file(COPY "${GARGANTUAN_PACKAGE}/" DESTINATION "${GARGANTUAN_INCOMPATIBLE}")
file(READ "${GARGANTUAN_INCOMPATIBLE}/game.package.json" GARGANTUAN_INCOMPATIBLE_MANIFEST)
string(JSON GARGANTUAN_INCOMPATIBLE_MANIFEST SET "${GARGANTUAN_INCOMPATIBLE_MANIFEST}" RuntimeCompatibility 2)
file(WRITE "${GARGANTUAN_INCOMPATIBLE}/game.package.json" "${GARGANTUAN_INCOMPATIBLE_MANIFEST}")
GargantuanExpectRejectedPackage("${GARGANTUAN_INCOMPATIBLE}" "an incompatible runtime manifest")

set(GARGANTUAN_MISSING_SHADER "${GARGANTUAN_WORKSPACE}/MissingShaderGame")
file(COPY "${GARGANTUAN_PACKAGE}/" DESTINATION "${GARGANTUAN_MISSING_SHADER}")
file(REMOVE "${GARGANTUAN_MISSING_SHADER}/shaders/gui.frag.spv")
GargantuanExpectRejectedPackage("${GARGANTUAN_MISSING_SHADER}" "a package with a missing shader")

set(GARGANTUAN_CORRUPT_ASSET "${GARGANTUAN_WORKSPACE}/CorruptAssetGame")
file(COPY "${GARGANTUAN_PACKAGE}/" DESTINATION "${GARGANTUAN_CORRUPT_ASSET}")
file(GLOB GARGANTUAN_ASSET_FILES "${GARGANTUAN_CORRUPT_ASSET}/content/assets/artifacts/*.gasset")
list(LENGTH GARGANTUAN_ASSET_FILES GARGANTUAN_ASSET_COUNT)
if(GARGANTUAN_ASSET_COUNT EQUAL 0)
	GargantuanPackageFailure("FirstCompleteGame package contains no canonical asset artifacts")
endif()
list(GET GARGANTUAN_ASSET_FILES 0 GARGANTUAN_CORRUPT_ASSET_FILE)
file(APPEND "${GARGANTUAN_CORRUPT_ASSET_FILE}" "corrupt")
GargantuanExpectRejectedPackage("${GARGANTUAN_CORRUPT_ASSET}" "a package with a corrupt asset")

file(REMOVE_RECURSE "${GARGANTUAN_WORKSPACE}")
message(STATUS "FirstCompleteGame package build/validate/inspect/relocation/startup/rejection smoke passed")
