#pragma once
#include <algorithm>
#include <array>
#include <cstdint>
#include <iostream>
#include <limits>
#include <optional>
#include <stdexcept>
#include <string_view>
namespace gargantuan::test::reliable_feedback_model {
using U=std::uint64_t; constexpr U KiB=1024,MiB=1024*KiB,G=512*KiB,DrainFloor=16*MiB,FreshnessUs=50'000;
enum class SegmentState:std::uint8_t{Pending,InFlight,Retry,Acked}; enum class FeedbackState:std::uint8_t{Missing,Fresh,Stale,Contradictory,Terminal};
struct Message{U PayloadBytes=0,ReliableHeaderBytes=0;SegmentState State=SegmentState::Pending;bool PayloadRetired=false;};
struct Snapshot{std::uint32_t Generation=0;U ObservedAtUs=0,UniqueReliableStreamBytesAcked=0,ReliablePayloadBytesAcked=0,ReliableStreamBytesRetransmitted=0,PendingReliableStreamBytes=0,SentUnackedReliableStreamBytes=0;FeedbackState State=FeedbackState::Missing;};
class Model{public:explicit Model(std::uint32_t g=1):Generation(g){if(!g)throw std::invalid_argument("generation");}std::size_t Submit(U p,U h=3){if(!p||p>G||h>16)throw std::invalid_argument("message");if(Count==Messages.size())throw std::overflow_error("message-cap");auto&m=Messages[Count];m={p,h};Pending+=p+h;CreatedPayload+=p;return Count++;}void FirstSend(std::size_t i){auto&m=At(i);Req(m.State==SegmentState::Pending,"first");U s=Stream(m);Req(Pending>=s,"pending");Pending-=s;Unacked+=s;FirstPhysical+=s;m.State=SegmentState::InFlight;}void MarkLostForRetry(std::size_t i){auto&m=At(i);Req(m.State==SegmentState::InFlight,"loss");U s=Stream(m);Req(Unacked>=s,"unacked");Unacked-=s;Pending+=s;m.State=SegmentState::Retry;}void Retransmit(std::size_t i){auto&m=At(i);Req(m.State==SegmentState::Retry,"retry");U s=Stream(m);Req(Pending>=s,"retry pending");Pending-=s;Unacked+=s;RetransPhysical+=s;m.State=SegmentState::InFlight;}void Ack(std::size_t i,U at){auto&m=At(i);Req(m.State==SegmentState::InFlight||m.State==SegmentState::Retry,"ack");U s=Stream(m);if(m.State==SegmentState::InFlight){Req(Unacked>=s,"ack unacked");Unacked-=s;}else{Req(Pending>=s,"ack pending");Pending-=s;}m.State=SegmentState::Acked;Add(UniqueStreamAcked,s);if(!m.PayloadRetired){m.PayloadRetired=true;Add(PayloadAcked,m.PayloadBytes);}LastAckAtUs=at;}void DuplicateAck(std::size_t i,U at){auto&m=At(i);Req(m.State==SegmentState::Acked,"dup");LastAckAtUs=at;}void TerminalRelease(){Terminal=true;U o=CreatedPayload-PayloadAcked-TerminalReleased;Add(TerminalReleased,o);Pending=Unacked=0;for(std::size_t i=0;i<Count;++i)if(Messages[i].State!=SegmentState::Acked)Messages[i].State=SegmentState::Acked;}Snapshot Observe(U at)const{return{Generation,at,UniqueStreamAcked,PayloadAcked,RetransPhysical,Pending,Unacked,Terminal?FeedbackState::Terminal:FeedbackState::Fresh};}U Created()const{return CreatedPayload;}U Drained()const{return PayloadAcked;}U Released()const{return TerminalReleased;}U Outstanding()const{return CreatedPayload-PayloadAcked-TerminalReleased;}U StreamAcked()const{return UniqueStreamAcked;}U Retransmitted()const{return RetransPhysical;}U PendingBytes()const{return Pending;}U UnackedBytes()const{return Unacked;}U PhysicalBytesSent()const{return FirstPhysical+RetransPhysical;}bool Conserved()const{return CreatedPayload==PayloadAcked+TerminalReleased+Outstanding();}
private:std::array<Message,16>Messages{};std::size_t Count=0;std::uint32_t Generation=0;U CreatedPayload=0,PayloadAcked=0,TerminalReleased=0,UniqueStreamAcked=0,FirstPhysical=0,RetransPhysical=0,Pending=0,Unacked=0;std::optional<U>LastAckAtUs;bool Terminal=false;Message&At(std::size_t i){if(i>=Count)throw std::out_of_range("message");return Messages[i];}static U Stream(const Message&m){if(m.PayloadBytes>std::numeric_limits<U>::max()-m.ReliableHeaderBytes)throw std::overflow_error("stream");return m.PayloadBytes+m.ReliableHeaderBytes;}static void Add(U&t,U d){if(d>std::numeric_limits<U>::max()-t)throw std::overflow_error("counter");t+=d;}static void Req(bool v,const char*w){if(!v)throw std::runtime_error(w);}};
struct Qualifier{std::uint32_t Generation=0;std::optional<Snapshot>Previous;bool Qualified=false,BootstrapGrantAvailable=true;bool AcceptSample(const Snapshot&s){if(!s.Generation||(Generation&&s.Generation!=Generation)){Reset(s.Generation);Previous=s;return false;}if(!Generation)Generation=s.Generation;if(s.State!=FeedbackState::Fresh){Qualified=false;Previous=s;return false;}if(Previous){if(s.ObservedAtUs<Previous->ObservedAtUs||s.UniqueReliableStreamBytesAcked<Previous->UniqueReliableStreamBytesAcked||s.ReliablePayloadBytesAcked<Previous->ReliablePayloadBytesAcked||s.ReliableStreamBytesRetransmitted<Previous->ReliableStreamBytesRetransmitted){Qualified=false;Previous=s;return false;}U dt=s.ObservedAtUs-Previous->ObservedAtUs,db=s.UniqueReliableStreamBytesAcked-Previous->UniqueReliableStreamBytesAcked;if(dt&&dt<=FreshnessUs){__uint128_t l=(__uint128_t)db*1'000'000u,r=(__uint128_t)DrainFloor*dt;Qualified=l>=r;}else Qualified=false;}Previous=s;return Qualified;}bool MayIssueGrant(bool debt,bool wants){if(!wants||debt)return false;if(Qualified)return true;if(BootstrapGrantAvailable){BootstrapGrantAvailable=false;return true;}return false;}void Reset(std::uint32_t g){Generation=g;Previous.reset();Qualified=false;BootstrapGrantAvailable=true;}};
inline void C(bool v,std::string_view w){if(!v)throw std::runtime_error(std::string(w));}
inline bool RunReliableTransportFeedbackModelTests(){std::size_t passed=0;auto T=[&](const char*n,auto f){try{f();++passed;std::cout<<"[ReliableFeedbackModel] "<<n<<"=pass\n";}catch(const std::exception&e){std::cerr<<"[ReliableFeedbackModel] "<<n<<"=FAIL "<<e.what()<<'\n';throw;}};try{
T("UniqueFirstSendDrain",[]{Model m;auto i=m.Submit(64*KiB);m.FirstSend(i);m.Ack(i,10'000);C(m.Drained()==64*KiB&&m.StreamAcked()>m.Drained()&&m.Conserved(),"unique");});
T("OneRetransmission",[]{Model m;auto i=m.Submit(64*KiB);m.FirstSend(i);m.MarkLostForRetry(i);m.Retransmit(i);m.Ack(i,20'000);C(m.Drained()==64*KiB&&m.Retransmitted()>0&&m.Conserved(),"retry");});
T("RepeatedRetransmissions",[]{Model m;auto i=m.Submit(G);m.FirstSend(i);for(int n=0;n<3;++n){m.MarkLostForRetry(i);m.Retransmit(i);}m.Ack(i,40'000);C(m.Drained()==G&&m.StreamAcked()==G+3&&m.PhysicalBytesSent()>2*G&&m.Conserved(),"repeat");});
T("DelayedAck",[]{Model m;auto i=m.Submit(G);m.FirstSend(i);auto b=m.Observe(40'000);m.Ack(i,80'000);C(b.ReliablePayloadBytesAcked==0&&m.Drained()==G,"delayed");});
T("DuplicateAck",[]{Model m;auto i=m.Submit(8*KiB);m.FirstSend(i);m.Ack(i,10'000);auto a=m.Drained(),s=m.StreamAcked();m.DuplicateAck(i,11'000);C(m.Drained()==a&&m.StreamAcked()==s,"dup");});
T("AckAfterRetransmission",[]{Model m;auto i=m.Submit(8*KiB);m.FirstSend(i);m.MarkLostForRetry(i);m.Retransmit(i);m.Ack(i,15'000);C(m.Drained()==8*KiB&&m.Retransmitted()==8*KiB+3,"ack retry");});
T("QueueBytesReenterPending",[]{Model m;auto i=m.Submit(32*KiB);auto p=m.PendingBytes();m.FirstSend(i);C(m.PendingBytes()==0&&m.UnackedBytes()==p,"send");m.MarkLostForRetry(i);C(m.PendingBytes()==p&&m.UnackedBytes()==0,"reenter");m.Retransmit(i);C(m.PendingBytes()+m.UnackedBytes()==p,"sum");});
T("PeerDrainsAtFloor",[]{Qualifier q;Snapshot a{.Generation=1,.ObservedAtUs=0,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.ObservedAtUs=25'000;b.UniqueReliableStreamBytesAcked=410*KiB;C(q.AcceptSample(b),"floor");});
T("PeerDrainsBelowFloor",[]{Qualifier q;Snapshot a{.Generation=1,.ObservedAtUs=0,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.ObservedAtUs=25'000;b.UniqueReliableStreamBytesAcked=300*KiB;C(!q.AcceptSample(b),"below");});
T("IdlePeer",[]{Qualifier q;Snapshot a{.Generation=1,.ObservedAtUs=0,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.ObservedAtUs=25'000;C(!q.AcceptSample(b)&&!q.Qualified,"idle");});
T("FirstGrantBootstrap",[]{Qualifier q;C(q.MayIssueGrant(false,true),"first");C(!q.MayIssueGrant(false,true),"one");});
T("DrainedSlowPeerRequalification",[]{Qualifier q;C(q.MayIssueGrant(false,true),"boot");Snapshot a{.Generation=1,.ObservedAtUs=0,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.ObservedAtUs=25'000;b.UniqueReliableStreamBytesAcked=200*KiB;C(!q.AcceptSample(b),"slow");C(!q.MayIssueGrant(false,true),"deny");auto c=b;c.ObservedAtUs=45'000;c.UniqueReliableStreamBytesAcked+=400*KiB;C(q.AcceptSample(c)&&q.MayIssueGrant(false,true),"requal");});
T("StaleFeedback",[]{Qualifier q;Snapshot a{.Generation=1,.ObservedAtUs=0,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.ObservedAtUs=FreshnessUs+1;b.UniqueReliableStreamBytesAcked=G;C(!q.AcceptSample(b),"stale");});
T("MissingFeedback",[]{Qualifier q;Snapshot a{.Generation=1,.State=FeedbackState::Missing};C(!q.AcceptSample(a),"missing");});
T("ConnectionTeardown",[]{Model m;auto a=m.Submit(100*KiB),b=m.Submit(200*KiB);m.FirstSend(a);m.Ack(a,10'000);m.FirstSend(b);m.TerminalRelease();C(m.Drained()==100*KiB&&m.Released()==200*KiB&&m.Outstanding()==0&&m.Conserved(),"terminal");});
T("ReconnectNewGeneration",[]{Qualifier q;Snapshot a{.Generation=1,.ObservedAtUs=0,.UniqueReliableStreamBytesAcked=G,.ReliablePayloadBytesAcked=G,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.Generation=2;b.ObservedAtUs=1;b.UniqueReliableStreamBytesAcked=0;b.ReliablePayloadBytesAcked=0;C(!q.AcceptSample(b)&&q.Generation==2&&!q.Qualified&&q.BootstrapGrantAvailable,"gen");});
T("CounterResetWrap",[]{Qualifier q;Snapshot a{.Generation=1,.ObservedAtUs=0,.UniqueReliableStreamBytesAcked=1000,.ReliablePayloadBytesAcked=900,.State=FeedbackState::Fresh};q.AcceptSample(a);auto b=a;b.ObservedAtUs=10'000;b.UniqueReliableStreamBytesAcked=999;C(!q.AcceptSample(b)&&!q.Qualified,"reset");});
T("TransportFailure",[]{Qualifier q;Snapshot a{.Generation=1,.State=FeedbackState::Contradictory};C(!q.AcceptSample(a),"failure");Model m;auto i=m.Submit(G);m.FirstSend(i);m.TerminalRelease();C(m.Drained()==0&&m.Released()==G&&m.Conserved(),"release");});
T("LogicalDebtPhysicalCostSeparated",[]{Model m;auto i=m.Submit(G);m.FirstSend(i);m.MarkLostForRetry(i);m.Retransmit(i);m.MarkLostForRetry(i);m.Retransmit(i);m.Ack(i,30'000);C(m.Created()==G&&m.Drained()==G&&m.PhysicalBytesSent()>2*G&&m.Conserved(),"separate");});
}catch(...){return false;}std::cout<<"[ReliableFeedbackModel] result=pass tests="<<passed<<'\n';return passed==19;}
}
