# Narrow local correction for KI-008; keep the immutable GNS revision.
# See devdocs/CurrentArchitecture/GnsPacketSequenceAttribution3L.md.
set(GnsThinkerPath "${gamenetworkingsockets_SOURCE_DIR}/src/steamnetworkingsockets/steamnetworkingsockets_thinker.cpp")
file(READ "${GnsThinkerPath}" GnsThinkerSource)
string(REPLACE "\r\n" "\n" GnsThinkerSource "${GnsThinkerSource}")
set(GnsOldEntry "void IThinker::Thinker_ProcessThinkers()\n{\n\t// We need the lock to access the thinker queue")
set(GnsNewEntry "void IThinker::Thinker_ProcessThinkers()\n{\n\t// Gargantuan KI-008: service only timers due when this pass began.\n\t// Keep fresh callback timestamps below, but return to socket reads before\n\t// servicing timers that became due while this batch was executing.\n\tconst SteamNetworkingMicroseconds usecEligibilityCutoff = SteamNetworkingSockets_GetLocalTimestamp();\n\t// We need the lock to access the thinker queue")
set(GnsOldCheck "if ( pNextThinker->GetNextThinkTime() >= usecNow )")
set(GnsNewCheck "if ( pNextThinker->GetNextThinkTime() >= usecEligibilityCutoff )")
string(REPLACE "${GnsNewEntry}" "${GnsOldEntry}" GnsOriginalSource "${GnsThinkerSource}")
string(REPLACE "${GnsNewCheck}" "${GnsOldCheck}" GnsOriginalSource "${GnsOriginalSource}")
string(SHA256 GnsOriginalHash "${GnsOriginalSource}")
if(NOT GnsOriginalHash STREQUAL "3173e3850d9ce7ad479f799f2e60daaffbbfbfc225605e7d22310911baee1613")
	message(FATAL_ERROR "GNS thinker source differs from the pinned KI-008 correction input")
endif()
string(FIND "${GnsThinkerSource}" "${GnsNewEntry}" GnsAlreadyPatched)
if(GnsAlreadyPatched EQUAL -1)
	string(FIND "${GnsThinkerSource}" "${GnsOldEntry}" GnsEntryPosition)
	string(FIND "${GnsThinkerSource}" "${GnsOldCheck}" GnsCheckPosition)
	if(GnsEntryPosition EQUAL -1 OR GnsCheckPosition EQUAL -1)
		message(FATAL_ERROR "Pinned GNS thinker source does not match the KI-008 correction")
	endif()
	string(REPLACE "${GnsOldEntry}" "${GnsNewEntry}" GnsThinkerSource "${GnsThinkerSource}")
	string(REPLACE "${GnsOldCheck}" "${GnsNewCheck}" GnsThinkerSource "${GnsThinkerSource}")
	file(WRITE "${GnsThinkerPath}" "${GnsThinkerSource}")
else()
	string(FIND "${GnsThinkerSource}" "${GnsNewCheck}" GnsCheckPosition)
	if(GnsCheckPosition EQUAL -1)
		message(FATAL_ERROR "Pinned GNS has an incomplete KI-008 correction")
	endif()
endif()
