if(NOT DEFINED GARGANTUAN_SHADER_SOURCE_DIR OR NOT DEFINED GARGANTUAN_SHADER_RUNTIME_DIR)
	message(FATAL_ERROR "Shader source and runtime directories are required")
endif()

file(GLOB GARGANTUAN_REQUIRED_SHADERS
	"${GARGANTUAN_SHADER_SOURCE_DIR}/*.vert"
	"${GARGANTUAN_SHADER_SOURCE_DIR}/*.frag"
)
if(NOT GARGANTUAN_REQUIRED_SHADERS)
	message(FATAL_ERROR "No required Gargantuan shaders were found")
endif()

foreach(GARGANTUAN_SHADER IN LISTS GARGANTUAN_REQUIRED_SHADERS)
	get_filename_component(GARGANTUAN_SHADER_NAME "${GARGANTUAN_SHADER}" NAME)
	set(GARGANTUAN_STAGED_SHADER "${GARGANTUAN_SHADER_RUNTIME_DIR}/${GARGANTUAN_SHADER_NAME}.spv")
	if(NOT EXISTS "${GARGANTUAN_STAGED_SHADER}")
		message(FATAL_ERROR "Required runtime shader is missing: ${GARGANTUAN_STAGED_SHADER}")
	endif()
endforeach()
